# workspace image for Gitpod
# image: gitpod/workspace-full:latest

# tasks to run when the workspace starts
tasks:
  - name: aws-cli
    before:
      echo 'install aws-cli'
      cd /workspaces
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $PWD
      # cd /workspaces/aws-saa-c03

# list ports to expose
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview